Update check and build.yml

diff --git a/.github/workflows/check and build.yml b/.github/workflows/check and build.yml
--- a/.github/workflows/check and build.yml
+++ b/.github/workflows/check and build.yml
@@ -1,131 +1,72 @@
-name: Build One-Hub
+name: Daily Build and Deploy
 
 on:
   schedule:
-    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
-  workflow_dispatch: # 手动触发 workflow
+    - cron: '0 0 * * *' # 每天午夜（UTC时间）执行
+  workflow_dispatch:
 
 jobs:
-  build:
+  build-and-deploy:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-        arch: [x64, x86, arm64, arm]
-        include:
-          - os: windows-latest
-            arch: x64
-            artifact_name: one-hub-windows-amd64.zip
-          - os: windows-latest
-            arch: x86
-            artifact_name: one-hub-windows-386.zip
-          - os: ubuntu-latest
-            arch: x64
-            artifact_name: one-hub-linux-amd64.tar.gz
-          - os: ubuntu-latest
-            arch: x86
-            artifact_name: one-hub-linux-i686.tar.gz
-          - os: ubuntu-latest
+        os: [linux, windows, freebsd]
+        arch: [amd64, 386, arm64] # 添加 arm64
+        exclude:
+          - os: windows
             arch: arm64
-            artifact_name: one-hub-linux-arm64.tar.gz
-          - os: ubuntu-latest
-            arch: arm
-            artifact_name: one-hub-linux-armv7l.tar.gz
-          - os: macos-latest
+          - os: freebsd
+            arch: 386
+          - os: freebsd
             arch: arm64
-            artifact_name: one-hub-darwin-arm64.tar.gz
-          - os: macos-latest
-            arch: x64
-            artifact_name: one-hub-darwin-amd64.tar.gz
-          - os: ubuntu-latest
-            arch: x64
-            target_os: freebsd
-            artifact_name: one-hub-freebsd-amd64.tar.gz
-
     steps:
-      - name: Checkout MartialBE/one-hub
-        uses: actions/checkout@v3
-        with:
-          repository: MartialBE/one-hub
-          ref: main # 或者你想要checkout的分支/tag
-          fetch-depth: 0 # 获取所有提交记录，用于比较tag
-
-      - name: Get Latest Tag
-        id: get_latest_tag
+      - name: Get latest versions
+        id: get_versions
         run: |
-          latest_tag=$(git describe --tags --abbrev=0 || echo "0")
-          echo "::set-output name=tag::$latest_tag"
-
-      - name: Checkout maohais/build-one-hub (用于获取之前的tag)
-        uses: actions/checkout@v3
-        with:
-          path: build-repo # checkout到build-repo文件夹
-          fetch-depth: 0
-
-      - name: Get Previous Release Tag
-        id: get_previous_tag
-        run: |
-          cd build-repo
-          previous_tag=$(git describe --tags --abbrev=0 || echo "0")
-          echo "::set-output name=tag::$previous_tag"
-          cd .. # 切回workflow根目录
-
-      - name: Check if build is needed
-        id: check_build
-        run: |
-          if [[ "${{ steps.get_latest_tag.outputs.tag }}" != "${{ steps.get_previous_tag.outputs.tag }}" ]]; then
-            echo "::set-output name=needed::true"
+          one_api_version=$(curl -sSL -o /dev/null -w "%{http_code}" "https://api.github.com/repos/MartialBE/one-api/releases/latest" | grep 200 && echo $(curl -s "https://api.github.com/repos/MartialBE/one-api/releases/latest" | jq -r '.tag_name')) || echo "Failed to get one-api version"
+          current_version=$(curl -sSL -o /dev/null -w "%{http_code}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | grep 200 && echo $(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r '.tag_name')) || echo "Failed to get current version"
+          echo "Latest one-api version: $one_api_version"
+          echo "Latest current repository version: $current_version"
+          if [ "$one_api_version" != "" ] && [ "$current_version" != "" ]; then
+            should_build=$(if [[ "$one_api_version" != "$current_version" ]]; then echo true; else echo false; fi)
+            echo "Should build: $should_build"
+            echo "::set-output name=one_api_version::$one_api_version"
+            echo "::set-output name=current_version::$current_version"
+            echo "::set-output name=should_build::$should_build"
           else
-            echo "::set-output name=needed::false"
+            exit 1
           fi
 
-      - name: Set up build environment (Linux/macOS)
-        if: matrix.os != 'windows-latest' && matrix.target_os != 'freebsd' && steps.check_build.outputs.needed == 'true'
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y build-essential
+      - name: Set up Go
+        if: ${{ steps.get_versions.outputs.should_build == 'true' }}
+        uses: actions/setup-go@v2
+        with:
+          go-version: '^1.15'
 
-      - name: Build (FreeBSD)
-        if: matrix.target_os == 'freebsd' && steps.check_build.outputs.needed == 'true'
+      - name: Build
+        if: ${{ steps.get_versions.outputs.should_build == 'true' }}
         run: |
-          docker run --rm -v "$(pwd):/app" freebsd:latest sh -c "pkg update -f && pkg install -y make gcc tar gzip && cd /app && make"
+          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o "one-api-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.get_versions.outputs.one_api_version }}" github.com/MartialBE/one-api
 
-      - name: Build (Other OS)
-        if: matrix.os != 'windows-latest' && matrix.target_os != 'freebsd' && steps.check_build.outputs.needed == 'true'
-        shell: bash
-        run: |
-           make # 假设使用make构建
-           # 如果需要根据不同系统执行不同的构建命令，请在此处添加判断
-           #例如 if [[ "${{ matrix.os }}" == "macos-latest" ]]; then 具体macos的命令; fi
-
-      - name: Create Release Artifact (FreeBSD)
-        if: matrix.target_os == 'freebsd' && steps.check_build.outputs.needed == 'true'
-        run: |
-          tar czf ${{ matrix.artifact_name }} one-api
-
-      - name: Create Release Artifact (Other OS)
-        if: matrix.os != 'windows-latest' && matrix.target_os != 'freebsd' && steps.check_build.outputs.needed == 'true'
-        run: |
-            tar czf ${{ matrix.artifact_name }} one-api #假设所有非freebsd平台打包方式相同，不同请修改
-
-      - name: Create Release
+      - name: Create GitHub Release
+        if: ${{ steps.get_versions.outputs.should_build == 'true' }}
+        id: create_release
         uses: actions/create-release@v1
-        if: steps.check_build.outputs.needed == 'true'
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Actions 提供的 token
         with:
-          tag_name: ${{ steps.get_latest_tag.outputs.tag }}
-          release_name: Release ${{ steps.get_latest_tag.outputs.tag }}
-          draft: false
-          prerelease: false
+          tag_name: ${{ steps.get_versions.outputs.one_api_version }}
+          release_name: Release ${{ steps.get_versions.outputs.one_api_version }}
+          body: |
+            Release notes for ${{ steps.get_versions.outputs.one_api_version }}
 
-      - name: Upload Release Artifact
+      - name: Upload Release Asset
+        if: ${{ steps.get_versions.outputs.should_build == 'true' }}
         uses: actions/upload-release-asset@v1
-        if: steps.check_build.outputs.needed == 'true'
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Actions 提供的 token
         with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: ./${{ matrix.artifact_name }}
-          asset_name: ${{ matrix.artifact_name }}
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: one-api-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.get_versions.outputs.one_api_version }}
+          asset_name: one-api-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.get_versions.outputs.one_api_version }}
           asset_content_type: application/octet-stream
